import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Data 16 Tema Lengkap
const THEMES_DATA = [
  // 1. ROYAL PALACE (DARK)
  {
    id: 'champagne_gold',
    name: 'Champagne Gold',
    subtitle: 'Royal Luxury & Classic Gold Foil',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#c4a661',
    secondary: '#d4af37',
    bg: '#0a0a0b',
    cardBg: '#111115',
    textMain: '#e2e2e7',
    textMuted: '#94949e',
    border: '#1f1f27',
    accentBg: '#181820',
    goldFoil: 'linear-gradient(135deg, #e5c983 0%, #fff4c2 25%, #c4a661 50%, #fef3bd 75%, #a88432 100%)',
    button: 'bg-gradient-to-r from-[#c4a661] via-[#d4af37] to-[#b38728] hover:opacity-90 text-neutral-950 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#c4a661]/40 text-[#d4af37] hover:bg-[#1f1f27]',
    headerBg: 'bg-[#0a0a0b] text-[#e2e2e7]',
    previewGradient: 'from-[#c4a661] to-[#8a7238]',
    tags: 'royal,gold,champagne,mewah,klasik,gelap',
    sortOrder: 1,
  },
  {
    id: 'velvet_navy',
    name: 'Velvet Navy',
    subtitle: 'Midnight Deep Blue & Gold Glow',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#243b61',
    secondary: '#d4af37',
    bg: '#070a12',
    cardBg: '#0d1524',
    textMain: '#e2e8f0',
    textMuted: '#889bb4',
    border: '#182740',
    accentBg: '#121c2e',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff3b0 30%, #aa771c 70%, #f5d77f 100%)',
    button: 'bg-gradient-to-r from-[#243b61] via-[#355384] to-[#1a2d4b] hover:opacity-90 text-amber-200 border border-amber-400/40 shadow-lg shadow-black/50',
    secondaryButton: 'border-amber-400/40 text-amber-300 hover:bg-[#121c2e]',
    headerBg: 'bg-[#070a12] text-slate-100',
    previewGradient: 'from-[#243b61] to-[#0f1b2d]',
    tags: 'navy,blue,midnight,royal,gold',
    sortOrder: 2,
  },
  {
    id: 'crimson_ruby',
    name: 'Crimson Ruby',
    subtitle: 'Deep Royal Ruby & Golden Crest',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#851e2b',
    secondary: '#d4af37',
    bg: '#0d0507',
    cardBg: '#170a0d',
    textMain: '#faedf0',
    textMuted: '#b8949a',
    border: '#2a1016',
    accentBg: '#220b10',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff4c2 30%, #851e2b 70%, #aa771c 100%)',
    button: 'bg-gradient-to-r from-[#851e2b] via-[#a32838] to-[#66131e] hover:opacity-90 text-amber-100 border border-amber-400/30 shadow-lg shadow-black/50',
    secondaryButton: 'border-amber-400/40 text-amber-300 hover:bg-[#220b10]',
    headerBg: 'bg-[#0d0507] text-red-100',
    previewGradient: 'from-[#851e2b] to-[#450911]',
    tags: 'crimson,ruby,maroon,red,royal,gold',
    sortOrder: 3,
  },

  // 2. ROYAL PALACE & LIGHT LUXURY
  {
    id: 'ivory_gold',
    name: 'Ivory Gold Pearl',
    subtitle: 'Sacred White Pearl & Champagne Gold Foil',
    category: 'royal',
    mode: 'light',
    archetype: 'royal_arch',
    primary: '#bfa15f',
    secondary: '#d4af37',
    bg: '#faf8f5',
    cardBg: '#ffffff',
    textMain: '#1c1c22',
    textMuted: '#666675',
    border: '#eae4d6',
    accentBg: '#f4eee4',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff4c2 30%, #bfa15f 70%, #aa771c 100%)',
    button: 'bg-gradient-to-r from-[#bfa15f] via-[#d4af37] to-[#a88944] hover:opacity-95 text-neutral-950 font-bold shadow-md shadow-amber-900/10',
    secondaryButton: 'border-[#bfa15f]/40 text-[#bfa15f] hover:bg-[#f4eee4]',
    headerBg: 'bg-[#faf8f5] text-neutral-900',
    previewGradient: 'from-[#fff4c2] via-[#e5c983] to-[#bfa15f]',
    tags: 'ivory,gold,pearl,putih,gading,akad,cerah,light',
    sortOrder: 4,
  },

  // 3. ADAT NUSANTARA
  {
    id: 'jawa_joglo',
    name: 'Jawa Klasik (Batik & Joglo)',
    subtitle: 'Gunungan Wayang, Batik Parang & Ukiran Jati Emas',
    category: 'traditional',
    mode: 'dark',
    archetype: 'jawa_joglo',
    primary: '#c4974f',
    secondary: '#e5c07b',
    bg: '#0f0c08',
    cardBg: '#1a140d',
    textMain: '#f7ede1',
    textMuted: '#ad9c87',
    border: '#382a19',
    accentBg: '#261c10',
    goldFoil: 'linear-gradient(135deg, #e5c07b 0%, #fff0c7 30%, #c4974f 70%, #8c6224 100%)',
    button: 'bg-gradient-to-r from-[#9c6828] via-[#c4974f] to-[#734b18] hover:opacity-95 text-neutral-950 font-bold shadow-lg shadow-black/50 border border-amber-500/40',
    secondaryButton: 'border-amber-600/40 text-amber-300 hover:bg-[#261c10]',
    headerBg: 'bg-[#0f0c08] text-amber-100',
    previewGradient: 'from-[#c4974f] via-[#734b18] to-[#261c10]',
    tags: 'jawa,joglo,wayang,gunungan,batik,parang,keraton,adat',
    sortOrder: 5,
  },
  {
    id: 'sunda_parahyangan',
    name: 'Sunda Parahyangan (Megamendung)',
    subtitle: 'Sejuk Pegunungan Priangan & Aksen Melati Ronce',
    category: 'traditional',
    mode: 'light',
    archetype: 'sunda_parahyangan',
    primary: '#2d6a4f',
    secondary: '#52b788',
    bg: '#f4f9f6',
    cardBg: '#ffffff',
    textMain: '#132a1f',
    textMuted: '#4f7362',
    border: '#d0e5da',
    accentBg: '#e6f2eb',
    goldFoil: 'linear-gradient(135deg, #52b788 0%, #d8f3dc 30%, #2d6a4f 70%, #1b4332 100%)',
    button: 'bg-gradient-to-r from-[#2d6a4f] via-[#40916c] to-[#1b4332] hover:opacity-95 text-white font-bold shadow-md shadow-emerald-950/15',
    secondaryButton: 'border-[#2d6a4f]/40 text-[#2d6a4f] hover:bg-[#e6f2eb]',
    headerBg: 'bg-[#f4f9f6] text-neutral-900',
    previewGradient: 'from-[#b7e4c7] via-[#52b788] to-[#2d6a4f]',
    tags: 'sunda,priangan,megamendung,melati,parahyangan,adat,hijau',
    sortOrder: 6,
  },
  {
    id: 'minang_suntiang',
    name: 'Minang Suntiang (Rumah Gadang)',
    subtitle: 'Kemegahan Emas Merah Ranah Minang & Gonjong Lima',
    category: 'traditional',
    mode: 'dark',
    archetype: 'minang_suntiang',
    primary: '#b91c1c',
    secondary: '#d4af37',
    bg: '#0d0406',
    cardBg: '#1c080b',
    textMain: '#fde8ea',
    textMuted: '#be8f94',
    border: '#3d1218',
    accentBg: '#2a0c10',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff3b0 30%, #b91c1c 70%, #aa771c 100%)',
    button: 'bg-gradient-to-r from-[#b91c1c] via-[#d4af37] to-[#881313] hover:opacity-95 text-neutral-950 font-bold shadow-lg shadow-black/50 border border-amber-400/40',
    secondaryButton: 'border-amber-400/40 text-amber-300 hover:bg-[#2a0c10]',
    headerBg: 'bg-[#0d0406] text-red-100',
    previewGradient: 'from-[#b91c1c] via-[#d4af37] to-[#1c080b]',
    tags: 'minang,padang,suntiang,gadang,gonjong,marawa,merah,adat',
    sortOrder: 7,
  },
  {
    id: 'bali_aesthetic',
    name: 'Bali Aesthetic (Kamboja & Candi)',
    subtitle: 'Gapura Candi Bentar, Bunga Kamboja & Janur Penjor',
    category: 'traditional',
    mode: 'light',
    archetype: 'bali_aesthetic',
    primary: '#ad6a28',
    secondary: '#dca458',
    bg: '#fcf8f2',
    cardBg: '#ffffff',
    textMain: '#281a0b',
    textMuted: '#735739',
    border: '#eedecb',
    accentBg: '#f8ede0',
    goldFoil: 'linear-gradient(135deg, #dca458 0%, #fff1da 30%, #ad6a28 70%, #7d4814 100%)',
    button: 'bg-gradient-to-r from-[#ad6a28] via-[#cf8b42] to-[#8a4e15] hover:opacity-95 text-amber-50 font-bold shadow-md shadow-amber-950/15',
    secondaryButton: 'border-[#ad6a28]/40 text-[#ad6a28] hover:bg-[#f8ede0]',
    headerBg: 'bg-[#fcf8f2] text-neutral-900',
    previewGradient: 'from-[#fae2c0] via-[#dca458] to-[#ad6a28]',
    tags: 'bali,candi,frangipani,kamboja,penjor,dewata,adat',
    sortOrder: 8,
  },
  {
    id: 'javanese_heritage',
    name: 'Javanese Heritage (Ningrat)',
    subtitle: 'Classic Keraton Ivory & Antique Gold Batik',
    category: 'traditional',
    mode: 'light',
    archetype: 'royal_arch',
    primary: '#9c6828',
    secondary: '#c79640',
    bg: '#fbf8f0',
    cardBg: '#ffffff',
    textMain: '#241a0e',
    textMuted: '#6b583e',
    border: '#e7dbbe',
    accentBg: '#f3ead3',
    goldFoil: 'linear-gradient(135deg, #c79640 0%, #fff7d6 30%, #9c6828 70%, #784e1b 100%)',
    button: 'bg-gradient-to-r from-[#9c6828] via-[#b88235] to-[#80521c] hover:opacity-95 text-amber-50 font-bold shadow-md shadow-amber-950/10',
    secondaryButton: 'border-[#9c6828]/40 text-[#9c6828] hover:bg-[#f3ead3]',
    headerBg: 'bg-[#fbf8f0] text-neutral-900',
    previewGradient: 'from-[#fcedcd] via-[#d6a95e] to-[#9c6828]',
    tags: 'jawa,ningrat,keraton,gading,ivory,batik,adat',
    sortOrder: 9,
  },

  // 4. ISLAMIC THEMES
  {
    id: 'emerald_sage',
    name: 'Emerald Sage',
    subtitle: 'Islamic Arabesque & Botanical Green',
    category: 'islamic',
    mode: 'dark',
    archetype: 'islamic_dome',
    primary: '#3a6b52',
    secondary: '#629e7c',
    bg: '#080c0a',
    cardBg: '#0e1612',
    textMain: '#e0ece4',
    textMuted: '#8ba395',
    border: '#192b20',
    accentBg: '#132119',
    goldFoil: 'linear-gradient(135deg, #629e7c 0%, #a2d6b7 30%, #3a6b52 70%, #b8e0c8 100%)',
    button: 'bg-gradient-to-r from-[#3a6b52] via-[#4d8668] to-[#2c533f] hover:opacity-90 text-emerald-50 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#3a6b52]/50 text-[#629e7c] hover:bg-[#132119]',
    headerBg: 'bg-[#080c0a] text-emerald-100',
    previewGradient: 'from-[#3a6b52] to-[#1e3b2c]',
    tags: 'islamic,emerald,sage,kubah,arabesque,hijau,syari',
    sortOrder: 10,
  },
  {
    id: 'botanical_sage',
    name: 'Botanical Sage Garden',
    subtitle: 'Fresh Olive Foliage & Organic Light Green',
    category: 'islamic',
    mode: 'light',
    archetype: 'islamic_dome',
    primary: '#43785d',
    secondary: '#73a58b',
    bg: '#f5f9f6',
    cardBg: '#ffffff',
    textMain: '#19261f',
    textMuted: '#587063',
    border: '#d7e6dc',
    accentBg: '#e8f2ec',
    goldFoil: 'linear-gradient(135deg, #73a58b 0%, #e2f2e9 30%, #43785d 70%, #2f5943 100%)',
    button: 'bg-gradient-to-r from-[#43785d] via-[#5c997a] to-[#325c46] hover:opacity-95 text-white font-bold shadow-md shadow-emerald-900/10',
    secondaryButton: 'border-[#43785d]/40 text-[#43785d] hover:bg-[#e8f2ec]',
    headerBg: 'bg-[#f5f9f6] text-neutral-900',
    previewGradient: 'from-[#daf0e3] via-[#8ec4a6] to-[#43785d]',
    tags: 'islamic,sage,botanical,olive,zaitun,cerah,light,syari',
    sortOrder: 11,
  },

  // 5. ROMANTIC & FLORAL
  {
    id: 'rose_gold',
    name: 'Rose Gold Blush',
    subtitle: 'Romantic Pastel & Soft Pink Glow',
    category: 'romantic',
    mode: 'dark',
    archetype: 'modern_glass',
    primary: '#b76e79',
    secondary: '#e8a598',
    bg: '#0f0a0c',
    cardBg: '#170f12',
    textMain: '#fae8eb',
    textMuted: '#bda1a6',
    border: '#2a1a1f',
    accentBg: '#211419',
    goldFoil: 'linear-gradient(135deg, #f3c1b8 0%, #fae8eb 30%, #b76e79 70%, #d48b94 100%)',
    button: 'bg-gradient-to-r from-[#b76e79] via-[#d48b94] to-[#99555e] hover:opacity-90 text-neutral-950 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#b76e79]/40 text-[#e8a598] hover:bg-[#211419]',
    headerBg: 'bg-[#0f0a0c] text-rose-100',
    previewGradient: 'from-[#b76e79] to-[#63353b]',
    tags: 'rose,gold,blush,pink,romantic,pastel',
    sortOrder: 12,
  },
  {
    id: 'soft_blush_floral',
    name: 'Soft Blush Floral',
    subtitle: 'Romantic Petal Pink & Rose Garden Glow',
    category: 'romantic',
    mode: 'light',
    archetype: 'modern_glass',
    primary: '#c4687d',
    secondary: '#e59ca8',
    bg: '#fcf8f9',
    cardBg: '#ffffff',
    textMain: '#26181d',
    textMuted: '#7a5e66',
    border: '#f2dee3',
    accentBg: '#faedf0',
    goldFoil: 'linear-gradient(135deg, #e59ca8 0%, #fff0f3 30%, #c4687d 70%, #b35267 100%)',
    button: 'bg-gradient-to-r from-[#c4687d] via-[#db8497] to-[#b35267] hover:opacity-95 text-white font-bold shadow-md shadow-rose-900/10',
    secondaryButton: 'border-[#c4687d]/40 text-[#c4687d] hover:bg-[#faedf0]',
    headerBg: 'bg-[#fcf8f9] text-neutral-900',
    previewGradient: 'from-[#ffe5eb] via-[#f7b5c4] to-[#c4687d]',
    tags: 'soft,blush,floral,pink,rose,garden,cerah,light',
    sortOrder: 13,
  },
  {
    id: 'terracotta_cream',
    name: 'Terracotta Bohemian',
    subtitle: 'Warm Earthy Sunset & Rustic Sand Dune',
    category: 'romantic',
    mode: 'light',
    archetype: 'royal_arch',
    primary: '#b35d3d',
    secondary: '#d98364',
    bg: '#faf6f2',
    cardBg: '#ffffff',
    textMain: '#2a1a14',
    textMuted: '#785b51',
    border: '#eddcd2',
    accentBg: '#f5ebe3',
    goldFoil: 'linear-gradient(135deg, #d98364 0%, #faeee8 30%, #b35d3d 70%, #914529 100%)',
    button: 'bg-gradient-to-r from-[#b35d3d] via-[#cc7352] to-[#99492d] hover:opacity-95 text-white font-bold shadow-md shadow-amber-900/10',
    secondaryButton: 'border-[#b35d3d]/40 text-[#b35d3d] hover:bg-[#f5ebe3]',
    headerBg: 'bg-[#faf6f2] text-neutral-900',
    previewGradient: 'from-[#fceade] via-[#e59b7e] to-[#b35d3d]',
    tags: 'terracotta,boho,earthy,rustic,sunset,cerah,light',
    sortOrder: 14,
  },

  // 6. MODERN MINIMALIST
  {
    id: 'midnight_obsidian',
    name: 'Midnight Obsidian',
    subtitle: 'Monochrome Luxe & Titanium Platinum',
    category: 'modern',
    mode: 'dark',
    archetype: 'modern_glass',
    primary: '#9ca3af',
    secondary: '#e5e7eb',
    bg: '#050505',
    cardBg: '#0d0d0f',
    textMain: '#f3f4f6',
    textMuted: '#71717a',
    border: '#1c1c20',
    accentBg: '#141417',
    goldFoil: 'linear-gradient(135deg, #e5e7eb 0%, #ffffff 30%, #9ca3af 70%, #d1d5db 100%)',
    button: 'bg-gradient-to-r from-zinc-700 via-zinc-600 to-zinc-800 hover:opacity-90 text-white font-bold border border-zinc-500/40 shadow-lg shadow-black/50',
    secondaryButton: 'border-zinc-700 text-zinc-300 hover:bg-[#141417]',
    headerBg: 'bg-[#050505] text-white',
    previewGradient: 'from-zinc-600 to-zinc-900',
    tags: 'monochrome,obsidian,titanium,modern,minimalist,black',
    sortOrder: 15,
  },
  {
    id: 'celestial_blue',
    name: 'Celestial Ice Blue',
    subtitle: 'Serene Powder Blue & Silver Crest',
    category: 'modern',
    mode: 'light',
    archetype: 'modern_glass',
    primary: '#3d6e94',
    secondary: '#6ba2cb',
    bg: '#f3f8fc',
    cardBg: '#ffffff',
    textMain: '#14202c',
    textMuted: '#586b7c',
    border: '#d2e3f0',
    accentBg: '#e4eff7',
    goldFoil: 'linear-gradient(135deg, #6ba2cb 0%, #e8f4fc 30%, #3d6e94 70%, #294e6b 100%)',
    button: 'bg-gradient-to-r from-[#3d6e94] via-[#5289b3] to-[#2b516f] hover:opacity-95 text-white font-bold shadow-md shadow-blue-900/10',
    secondaryButton: 'border-[#3d6e94]/40 text-[#3d6e94] hover:bg-[#e4eff7]',
    headerBg: 'bg-[#f3f8fc] text-neutral-900',
    previewGradient: 'from-[#d9eefc] via-[#83badf] to-[#3d6e94]',
    tags: 'blue,ice,celestial,sky,silver,cerah,light,modern',
    sortOrder: 16,
  },
];

// Data Style Kits
const STYLE_KITS_DATA = [
  {
    id: 'royal_gold_elegance',
    name: 'Royal Gold Elegance',
    category: 'royal',
    tagline: 'Kemewahan Kerajaan Klasik',
    themeId: 'champagne_gold',
    fontPairingId: 'royal_serif',
    frameShape: 'royal_arch',
    previewGradient: 'from-amber-600 via-yellow-500 to-amber-800',
    primaryColor: '#c4a661',
    description: 'Paduan foil emas mewah, font serif klasik Cinzel, dan bingkai lengkung Royal Arch.',
    badge: 'Paling Populer',
    tags: 'gold,royal,klasik',
    sortOrder: 1,
  },
  {
    id: 'ivory_pearl_royal',
    name: 'Ivory Pearl Sacred Gold',
    category: 'royal',
    tagline: 'Kemurnian Putih Gading & Emas',
    themeId: 'ivory_gold',
    fontPairingId: 'royal_serif',
    frameShape: 'royal_arch',
    previewGradient: 'from-amber-100 via-amber-200 to-amber-400',
    primaryColor: '#bfa15f',
    description: 'Latar putih gading bersih dipadu foil emas murni dan tipografi serif berwibawa.',
    badge: '☀️ Favorit Cerah',
    tags: 'ivory,gold,putih,cerah',
    sortOrder: 2,
  },
  {
    id: 'jawa_joglo_klasik',
    name: 'Jawa Klasik Joglo & Wayang',
    category: 'traditional',
    tagline: 'Filosofi Luhur Gunungan & Jati Emas',
    themeId: 'jawa_joglo',
    fontPairingId: 'nusantara_heritage',
    frameShape: 'jawa_joglo',
    previewGradient: 'from-amber-700 via-yellow-600 to-amber-950',
    primaryColor: '#c4974f',
    description: 'Mahakarya budaya Jawa dengan Gunungan Wayang, ornamen Prada Jawi, dan ukiran Joglo.',
    badge: '🏛️ Jawa Klasik',
    tags: 'jawa,joglo,wayang,gunungan',
    sortOrder: 3,
  },
  {
    id: 'sunda_priangan_megamendung',
    name: 'Sunda Parahyangan Megamendung',
    category: 'traditional',
    tagline: 'Kelembutan Awan & Bunga Melati Priangan',
    themeId: 'sunda_parahyangan',
    fontPairingId: 'romantic_calligraphy',
    frameShape: 'sunda_parahyangan',
    previewGradient: 'from-emerald-300 via-teal-400 to-emerald-700',
    primaryColor: '#2d6a4f',
    description: 'Nuansa alam Parahyangan yang asri dengan ornamen lengkung Megamendung dan harum melati.',
    badge: '🌸 Sunda Priangan',
    tags: 'sunda,megamendung,priangan',
    sortOrder: 4,
  },
  {
    id: 'minang_suntiang_gadang',
    name: 'Minang Suntiang Rumah Gadang',
    category: 'traditional',
    tagline: 'Keagungan Suntiang & Gonjong Ranah Minang',
    themeId: 'minang_suntiang',
    fontPairingId: 'royal_serif',
    frameShape: 'minang_suntiang',
    previewGradient: 'from-red-600 via-amber-500 to-red-950',
    primaryColor: '#b91c1c',
    description: 'Kemewahan adat Minangkabau dengan mahkota Suntiang emas dan 5 atap Gonjong megah.',
    badge: '👑 Minang Megah',
    tags: 'minang,suntiang,gadang',
    sortOrder: 5,
  },
  {
    id: 'bali_aesthetic_frangipani',
    name: 'Bali Aesthetic Candi Frangipani',
    category: 'traditional',
    tagline: 'Eksotisme Candi Bentar & Kamboja Bali',
    themeId: 'bali_aesthetic',
    fontPairingId: 'nusantara_heritage',
    frameShape: 'bali_aesthetic',
    previewGradient: 'from-amber-200 via-yellow-400 to-amber-700',
    primaryColor: '#ad6a28',
    description: 'Sentuhan Pulau Dewata yang magis dengan Gapura Candi Bentar, Bunga Kamboja, dan Janur.',
    badge: '🌿 Bali Exotic',
    tags: 'bali,candi,frangipani',
    sortOrder: 6,
  },
  {
    id: 'javanese_ningrat_gold',
    name: 'Javanese Ningrat Heritage',
    category: 'traditional',
    tagline: 'Keanggunan Adat Keraton Jawa',
    themeId: 'javanese_heritage',
    fontPairingId: 'royal_serif',
    frameShape: 'royal_arch',
    previewGradient: 'from-amber-100 via-yellow-200 to-amber-600',
    primaryColor: '#9c6828',
    description: 'Pesona adat Jawa ningrat berlatar gading dengan aksen batik prada emas klasik.',
    badge: '☀️ Tradisional',
    tags: 'jawa,ningrat,gading',
    sortOrder: 7,
  },
  {
    id: 'islamic_emerald_dome',
    name: 'Islamic Emerald Dome',
    category: 'islamic',
    tagline: 'Nuansa Islami Sakinah & Teduh',
    themeId: 'emerald_sage',
    fontPairingId: 'islamic_arabic',
    frameShape: 'islamic_dome',
    previewGradient: 'from-emerald-700 via-teal-600 to-emerald-900',
    primaryColor: '#2d8a68',
    description: 'Nuansa hijau sage sejuk dipadu tipografi Arabi Amiri dan bingkai Kubah Masjid.',
    badge: 'Favorit Syar’i',
    tags: 'islamic,dome,kubah,sage',
    sortOrder: 8,
  },
  {
    id: 'botanical_sage_light',
    name: 'Botanical Sage Syar’i Light',
    category: 'islamic',
    tagline: 'Kesejukan Daun Zaitun Islami',
    themeId: 'botanical_sage',
    fontPairingId: 'islamic_arabic',
    frameShape: 'islamic_dome',
    previewGradient: 'from-emerald-100 via-teal-200 to-emerald-400',
    primaryColor: '#43785d',
    description: 'Hijau sage terang alami dengan kaligrafi Arab elegan dan kubah masjid yang teduh.',
    badge: '☀️ Islami Cerah',
    tags: 'islamic,sage,cerah,zaitun',
    sortOrder: 9,
  },
  {
    id: 'romantic_rose_calligraphy',
    name: 'Romantic Rose Calligraphy',
    category: 'romantic',
    tagline: 'Sentuhan Kaligrafi Romantis Manis',
    themeId: 'rose_gold',
    fontPairingId: 'romantic_calligraphy',
    frameShape: 'soft_oval',
    previewGradient: 'from-rose-500 via-pink-400 to-rose-700',
    primaryColor: '#d67d8f',
    description: 'Blush pink hangat dipadu tulisan tangan bersambung Great Vibes dan bingkai oval lembut.',
    badge: 'Romantis',
    tags: 'rose,pink,calligraphy',
    sortOrder: 10,
  },
  {
    id: 'soft_blush_garden',
    name: 'Soft Blush Floral Romance',
    category: 'romantic',
    tagline: 'Taman Bunga Mawar Lembut',
    themeId: 'soft_blush_floral',
    fontPairingId: 'romantic_calligraphy',
    frameShape: 'soft_oval',
    previewGradient: 'from-pink-100 via-rose-200 to-rose-400',
    primaryColor: '#c4687d',
    description: 'Nuansa pastel pink manis dengan kaligrafi indah, sangat cocok untuk tema garden wedding.',
    badge: '☀️ Romantis Cerah',
    tags: 'blush,floral,pink,garden',
    sortOrder: 11,
  },
  {
    id: 'terracotta_boho_light',
    name: 'Terracotta Bohemian Sunset',
    category: 'romantic',
    tagline: 'Hangatnya Bumi & Senja Bohemian',
    themeId: 'terracotta_cream',
    fontPairingId: 'nusantara_heritage',
    frameShape: 'royal_arch',
    previewGradient: 'from-orange-100 via-amber-200 to-orange-400',
    primaryColor: '#b35d3d',
    description: 'Kombinasi warna terracotta hangat dengan background krem lembut dan tipografi elegan.',
    badge: '☀️ Rustic Boho',
    tags: 'terracotta,boho,rustic',
    sortOrder: 12,
  },
  {
    id: 'midnight_modern_clean',
    name: 'Midnight Modern Clean',
    category: 'modern',
    tagline: 'Kontemporer & Berkarakter Mewah',
    themeId: 'midnight_obsidian',
    fontPairingId: 'modern_clean',
    frameShape: 'double_border',
    previewGradient: 'from-neutral-700 via-neutral-800 to-black',
    primaryColor: '#a1a1aa',
    description: 'Dark obsidian premium dengan sans-serif Montserrat modern dan bingkai garis ganda.',
    badge: 'Modern Trend',
    tags: 'modern,obsidian,minimalist',
    sortOrder: 13,
  },
  {
    id: 'celestial_blue_modern',
    name: 'Celestial Ice Blue Modern',
    category: 'modern',
    tagline: 'Kesejukan Langit Biru & Silver',
    themeId: 'celestial_blue',
    fontPairingId: 'modern_clean',
    frameShape: 'double_border',
    previewGradient: 'from-blue-100 via-sky-200 to-blue-400',
    primaryColor: '#3d6e94',
    description: 'Nuansa biru es lembut kontemporer dengan garis ganda modern yang bersih dan segar.',
    badge: '☀️ Modern Cerah',
    tags: 'blue,modern,cerah',
    sortOrder: 14,
  },
  {
    id: 'playful_festive_party',
    name: 'Playful Festive Pastel',
    category: 'festive',
    tagline: 'Ceria, Dinamis & Berwarna',
    themeId: 'champagne_gold',
    fontPairingId: 'playful_party',
    frameShape: 'soft_oval',
    previewGradient: 'from-amber-400 via-pink-400 to-purple-500',
    primaryColor: '#d97706',
    description: 'Sangat cocok untuk pesta ulang tahun dan aqiqah dengan font Poppins yang riang.',
    badge: 'Ceria',
    tags: 'party,birthday,festive,ceria',
    sortOrder: 15,
  },
];

async function seed() {
  console.log('Seeding Themes & Style Kits to SQLite...');

  for (const th of THEMES_DATA) {
    const palette = {
      primary: th.primary,
      secondary: th.secondary,
      bg: th.bg,
      cardBg: th.cardBg,
      textMain: th.textMain,
      textMuted: th.textMuted,
      border: th.border,
      accentBg: th.accentBg,
      goldFoil: th.goldFoil,
      button: th.button,
      secondaryButton: th.secondaryButton,
      headerBg: th.headerBg,
      previewGradient: th.previewGradient,
    };

    await prisma.themePreset.upsert({
      where: { id: th.id },
      update: {
        name: th.name,
        subtitle: th.subtitle,
        category: th.category,
        mode: th.mode,
        archetype: th.archetype,
        paletteJson: JSON.stringify(palette),
        tags: th.tags,
        sortOrder: th.sortOrder,
        isActive: true,
      },
      create: {
        id: th.id,
        name: th.name,
        subtitle: th.subtitle,
        category: th.category,
        mode: th.mode,
        archetype: th.archetype,
        paletteJson: JSON.stringify(palette),
        tags: th.tags,
        sortOrder: th.sortOrder,
        isActive: true,
      },
    });
  }

  for (const kit of STYLE_KITS_DATA) {
    await prisma.styleKitPreset.upsert({
      where: { id: kit.id },
      update: {
        name: kit.name,
        category: kit.category,
        tagline: kit.tagline,
        themeId: kit.themeId,
        fontPairingId: kit.fontPairingId,
        frameShape: kit.frameShape,
        previewGradient: kit.previewGradient,
        primaryColor: kit.primaryColor,
        description: kit.description,
        badge: kit.badge,
        tags: kit.tags,
        sortOrder: kit.sortOrder,
        isActive: true,
      },
      create: {
        id: kit.id,
        name: kit.name,
        category: kit.category,
        tagline: kit.tagline,
        themeId: kit.themeId,
        fontPairingId: kit.fontPairingId,
        frameShape: kit.frameShape,
        previewGradient: kit.previewGradient,
        primaryColor: kit.primaryColor,
        description: kit.description,
        badge: kit.badge,
        tags: kit.tags,
        sortOrder: kit.sortOrder,
        isActive: true,
      },
    });
  }

  console.log('✅ Successfully seeded 16 Themes and 15 Style Kits into SQLite!');
}

seed()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
