[Interface]
PrivateKey = mCG1JpX5ikuBtXdp5LrSiSfKdVROP9gaV5TazVYCn2s=
Address = 10.0.2.3/32
DNS = 1.1.1.1

[Peer]
PublicKey = SP47bTGqXxN4Qqe2DewpONtYEOh2qcXPTj7dt1g1x2o=
Endpoint = 103.196.155.87:51820
AllowedIPs = 10.0.0.1/32
PersistentKeepalive = 25
