import { FastifyRequest, FastifyReply } from 'fastify';

export class ThemeController {
  // GET /api/themes - Get dynamic curated theme swatches
  static async getThemes(req: FastifyRequest, reply: FastifyReply) {
    const themes = [
      {
        id: 'champagne_gold',
        name: 'Champagne Gold',
        subtitle: 'Foil Emas Mewah Klasik',
        primary: '#c4a661',
        secondary: '#e5c985',
        bg: '#0a0a0b',
        cardBg: '#121216',
        accent: '#c4a661',
        previewGradient: 'from-amber-600 to-yellow-500',
      },
      {
        id: 'emerald_sage',
        name: 'Emerald Sage',
        subtitle: 'Hijau Botani Islami',
        primary: '#2d8a68',
        secondary: '#52b788',
        bg: '#061a14',
        cardBg: '#0b2920',
        accent: '#52b788',
        previewGradient: 'from-emerald-700 to-teal-500',
      },
      {
        id: 'velvet_navy',
        name: 'Velvet Navy',
        subtitle: 'Royal Deep Navy Blue',
        primary: '#3b82f6',
        secondary: '#93c5fd',
        bg: '#050c1a',
        cardBg: '#0c1830',
        accent: '#60a5fa',
        previewGradient: 'from-blue-900 to-indigo-600',
      },
      {
        id: 'rose_gold',
        name: 'Rose Gold',
        subtitle: 'Blush Pink Romantis',
        primary: '#d67d8f',
        secondary: '#f4acb7',
        bg: '#180d12',
        cardBg: '#2a1720',
        accent: '#f4acb7',
        previewGradient: 'from-rose-600 to-pink-400',
      },
      {
        id: 'midnight_obsidian',
        name: 'Midnight Obsidian',
        subtitle: 'Dark Monochrome Premium',
        primary: '#a1a1aa',
        secondary: '#e4e4e7',
        bg: '#09090b',
        cardBg: '#18181b',
        accent: '#d4d4d8',
        previewGradient: 'from-neutral-800 to-neutral-950',
      },
      {
        id: 'crimson_ruby',
        name: 'Crimson Ruby',
        subtitle: 'Merah Ruby Megah',
        primary: '#e11d48',
        secondary: '#fb7185',
        bg: '#140509',
        cardBg: '#280b13',
        accent: '#fb7185',
        previewGradient: 'from-rose-700 to-red-600',
      },
    ];

    return reply.status(200).send({
      success: true,
      data: themes,
      meta: { count: themes.length, cachedAt: new Date().toISOString() },
    });
  }

  // GET /api/style-kits - Get Master Style Kits
  static async getStyleKits(req: FastifyRequest, reply: FastifyReply) {
    const styleKits = [
      {
        id: 'royal_gold_elegance',
        name: 'Royal Gold Elegance',
        category: 'royal',
        tagline: 'Kemewahan Kerajaan Klasik',
        themeId: 'champagne_gold',
        fontPairingId: 'royal_serif',
        frameShape: 'royal_arch',
        previewGradient: 'from-amber-600 via-yellow-500 to-amber-800',
        primaryColor: '#c4a661',
        description: 'Paduan foil emas mewah, font serif klasik Cinzel, dan bingkai lengkung Royal Arch.',
        badge: 'Paling Populer',
      },
      {
        id: 'islamic_emerald_dome',
        name: 'Islamic Emerald Dome',
        category: 'islamic',
        tagline: 'Nuansa Islami Sakinah & Teduh',
        themeId: 'emerald_sage',
        fontPairingId: 'islamic_arabic',
        frameShape: 'islamic_dome',
        previewGradient: 'from-emerald-700 via-teal-600 to-emerald-900',
        primaryColor: '#2d8a68',
        description: 'Nuansa hijau sage sejuk dipadu tipografi Arabi Amiri dan bingkai Kubah Masjid.',
        badge: 'Favorit Syar’i',
      },
      {
        id: 'romantic_rose_calligraphy',
        name: 'Romantic Rose Calligraphy',
        category: 'romantic',
        tagline: 'Sentuhan Kaligrafi Romantis Manis',
        themeId: 'rose_gold',
        fontPairingId: 'romantic_calligraphy',
        frameShape: 'soft_oval',
        previewGradient: 'from-rose-500 via-pink-400 to-rose-700',
        primaryColor: '#d67d8f',
        description: 'Blush pink hangat dipadu tulisan tangan bersambung Great Vibes dan bingkai oval lembut.',
        badge: 'Romantis',
      },
      {
        id: 'midnight_modern_clean',
        name: 'Midnight Modern Clean',
        category: 'modern',
        tagline: 'Kontemporer & Berkarakter Mewah',
        themeId: 'midnight_obsidian',
        fontPairingId: 'modern_clean',
        frameShape: 'double_border',
        previewGradient: 'from-neutral-700 via-neutral-800 to-black',
        primaryColor: '#a1a1aa',
        description: 'Dark obsidian premium dengan sans-serif Montserrat modern dan bingkai garis ganda.',
        badge: 'Modern Trend',
      },
      {
        id: 'velvet_navy_classic',
        name: 'Velvet Navy Majestic',
        category: 'royal',
        tagline: 'Keagungan Biru Navy & Emas',
        themeId: 'velvet_navy',
        fontPairingId: 'royal_serif',
        frameShape: 'royal_arch',
        previewGradient: 'from-blue-900 via-indigo-800 to-slate-950',
        primaryColor: '#3b82f6',
        description: 'Deep navy keemasan dengan tipografi formal kerajaan yang sangat prestisius.',
        badge: 'Eksklusif',
      },
      {
        id: 'crimson_ruby_luxury',
        name: 'Crimson Ruby Palace',
        category: 'romantic',
        tagline: 'Merah Ruby Mewah & Berani',
        themeId: 'crimson_ruby',
        fontPairingId: 'royal_serif',
        frameShape: 'royal_arch',
        previewGradient: 'from-red-800 via-rose-700 to-red-950',
        primaryColor: '#e11d48',
        description: 'Merah ruby berani dan mewah yang melambangkan kebahagiaan dan pesta megah.',
        badge: 'Elegan',
      },
      {
        id: 'playful_festive_party',
        name: 'Playful Festive Pastel',
        category: 'festive',
        tagline: 'Ceria, Dinamis & Berwarna',
        themeId: 'champagne_gold',
        fontPairingId: 'playful_party',
        frameShape: 'soft_oval',
        previewGradient: 'from-amber-400 via-pink-400 to-purple-500',
        primaryColor: '#d97706',
        description: 'Sangat cocok untuk pesta ulang tahun dan aqiqah dengan font Poppins yang riang.',
        badge: 'Ceria',
      },
    ];

    return reply.status(200).send({
      success: true,
      data: styleKits,
      meta: { count: styleKits.length, cachedAt: new Date().toISOString() },
    });
  }
}
