import { ThemeDefinition, MasterStyleKitDefinition } from '../types';

export const ISLAMIC_THEMES: Record<string, ThemeDefinition> = {
  emerald_sage: {
    id: 'emerald_sage',
    name: 'Emerald Sage',
    subtitle: 'Islamic Arabesque & Botanical Green',
    category: 'islamic',
    mode: 'dark',
    archetype: 'islamic_dome',
    primary: '#3a6b52',
    secondary: '#629e7c',
    bg: '#080c0a',
    cardBg: '#0e1612',
    textMain: '#e0ece4',
    textMuted: '#8ba395',
    border: '#192b20',
    accentBg: '#132119',
    goldFoil: 'linear-gradient(135deg, #629e7c 0%, #a2d6b7 30%, #3a6b52 70%, #b8e0c8 100%)',
    button: 'bg-gradient-to-r from-[#3a6b52] via-[#4d8668] to-[#2c533f] hover:opacity-90 text-emerald-50 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#3a6b52]/50 text-[#629e7c] hover:bg-[#132119]',
    headerBg: 'bg-[#080c0a] text-emerald-100',
    previewGradient: 'from-[#3a6b52] to-[#1e3b2c]',
    tags: ['islamic', 'emerald', 'sage', 'kubah', 'arabesque', 'hijau', 'syari'],
    palette: {
      primary: '#3a6b52',
      secondary: '#629e7c',
      bg: '#080c0a',
      cardBg: '#0e1612',
      textMain: '#e0ece4',
      textMuted: '#8ba395',
      border: '#192b20',
      accentBg: '#132119',
      previewGradient: 'from-[#3a6b52] to-[#1e3b2c]',
    },
  },
  botanical_sage: {
    id: 'botanical_sage',
    name: 'Botanical Sage Garden',
    subtitle: 'Fresh Olive Foliage & Organic Light Green',
    category: 'islamic',
    mode: 'light',
    archetype: 'islamic_dome',
    primary: '#43785d',
    secondary: '#73a58b',
    bg: '#f5f9f6',
    cardBg: '#ffffff',
    textMain: '#19261f',
    textMuted: '#587063',
    border: '#d7e6dc',
    accentBg: '#e8f2ec',
    goldFoil: 'linear-gradient(135deg, #73a58b 0%, #e2f2e9 30%, #43785d 70%, #2f5943 100%)',
    button: 'bg-gradient-to-r from-[#43785d] via-[#5c997a] to-[#325c46] hover:opacity-95 text-white font-bold shadow-md shadow-emerald-900/10',
    secondaryButton: 'border-[#43785d]/40 text-[#43785d] hover:bg-[#e8f2ec]',
    headerBg: 'bg-[#f5f9f6] text-neutral-900',
    previewGradient: 'from-[#daf0e3] via-[#8ec4a6] to-[#43785d]',
    tags: ['islamic', 'sage', 'botanical', 'olive', 'zaitun', 'cerah', 'light', 'syari'],
    palette: {
      primary: '#43785d',
      secondary: '#73a58b',
      bg: '#f5f9f6',
      cardBg: '#ffffff',
      textMain: '#19261f',
      textMuted: '#587063',
      border: '#d7e6dc',
      accentBg: '#e8f2ec',
      previewGradient: 'from-[#daf0e3] via-[#8ec4a6] to-[#43785d]',
    },
  },
};

export const ISLAMIC_STYLE_KITS: Record<string, MasterStyleKitDefinition> = {
  islamic_emerald_dome: {
    id: 'islamic_emerald_dome',
    name: 'Islamic Emerald Dome',
    category: 'islamic',
    tagline: 'Nuansa Islami Sakinah & Teduh',
    themeId: 'emerald_sage',
    fontPairingId: 'islamic_arabic',
    frameShape: 'islamic_dome',
    previewGradient: 'from-emerald-700 via-teal-600 to-emerald-900',
    primaryColor: '#2d8a68',
    description: 'Nuansa hijau sage sejuk dipadu tipografi Arabi Amiri dan bingkai Kubah Masjid.',
    badge: 'Favorit Syar’i',
    tags: ['islamic', 'dome', 'kubah', 'sage'],
  },
  botanical_sage_light: {
    id: 'botanical_sage_light',
    name: 'Botanical Sage Syar’i Light',
    category: 'islamic',
    tagline: 'Kesejukan Daun Zaitun Islami',
    themeId: 'botanical_sage',
    fontPairingId: 'islamic_arabic',
    frameShape: 'islamic_dome',
    previewGradient: 'from-emerald-100 via-teal-200 to-emerald-400',
    primaryColor: '#43785d',
    description: 'Hijau sage terang alami dengan kaligrafi Arab elegan dan kubah masjid yang teduh.',
    badge: '☀️ Islami Cerah',
    tags: ['islamic', 'sage', 'cerah', 'zaitun'],
  },
};
