import { ThemeDefinition, MasterStyleKitDefinition } from '../types';

export const MODERN_THEMES: Record<string, ThemeDefinition> = {
  midnight_obsidian: {
    id: 'midnight_obsidian',
    name: 'Midnight Obsidian',
    subtitle: 'Monochrome Luxe & Titanium Platinum',
    category: 'modern',
    mode: 'dark',
    archetype: 'modern_glass',
    primary: '#9ca3af',
    secondary: '#e5e7eb',
    bg: '#050505',
    cardBg: '#0d0d0f',
    textMain: '#f3f4f6',
    textMuted: '#71717a',
    border: '#1c1c20',
    accentBg: '#141417',
    goldFoil: 'linear-gradient(135deg, #e5e7eb 0%, #ffffff 30%, #9ca3af 70%, #d1d5db 100%)',
    button: 'bg-gradient-to-r from-zinc-700 via-zinc-600 to-zinc-800 hover:opacity-90 text-white font-bold border border-zinc-500/40 shadow-lg shadow-black/50',
    secondaryButton: 'border-zinc-700 text-zinc-300 hover:bg-[#141417]',
    headerBg: 'bg-[#050505] text-white',
    previewGradient: 'from-zinc-600 to-zinc-900',
    tags: ['monochrome', 'obsidian', 'titanium', 'modern', 'minimalist', 'black'],
    palette: {
      primary: '#9ca3af',
      secondary: '#e5e7eb',
      bg: '#050505',
      cardBg: '#0d0d0f',
      textMain: '#f3f4f6',
      textMuted: '#71717a',
      border: '#1c1c20',
      accentBg: '#141417',
      previewGradient: 'from-zinc-600 to-zinc-900',
    },
  },
  celestial_blue: {
    id: 'celestial_blue',
    name: 'Celestial Ice Blue',
    subtitle: 'Serene Powder Blue & Silver Crest',
    category: 'modern',
    mode: 'light',
    archetype: 'modern_glass',
    primary: '#3d6e94',
    secondary: '#6ba2cb',
    bg: '#f3f8fc',
    cardBg: '#ffffff',
    textMain: '#14202c',
    textMuted: '#586b7c',
    border: '#d2e3f0',
    accentBg: '#e4eff7',
    goldFoil: 'linear-gradient(135deg, #6ba2cb 0%, #e8f4fc 30%, #3d6e94 70%, #294e6b 100%)',
    button: 'bg-gradient-to-r from-[#3d6e94] via-[#5289b3] to-[#2b516f] hover:opacity-95 text-white font-bold shadow-md shadow-blue-900/10',
    secondaryButton: 'border-[#3d6e94]/40 text-[#3d6e94] hover:bg-[#e4eff7]',
    headerBg: 'bg-[#f3f8fc] text-neutral-900',
    previewGradient: 'from-[#d9eefc] via-[#83badf] to-[#3d6e94]',
    tags: ['blue', 'ice', 'celestial', 'sky', 'silver', 'cerah', 'light', 'modern'],
    palette: {
      primary: '#3d6e94',
      secondary: '#6ba2cb',
      bg: '#f3f8fc',
      cardBg: '#ffffff',
      textMain: '#14202c',
      textMuted: '#586b7c',
      border: '#d2e3f0',
      accentBg: '#e4eff7',
      previewGradient: 'from-[#d9eefc] via-[#83badf] to-[#3d6e94]',
    },
  },
};

export const MODERN_STYLE_KITS: Record<string, MasterStyleKitDefinition> = {
  midnight_modern_clean: {
    id: 'midnight_modern_clean',
    name: 'Midnight Modern Clean',
    category: 'modern',
    tagline: 'Kontemporer & Berkarakter Mewah',
    themeId: 'midnight_obsidian',
    fontPairingId: 'modern_clean',
    frameShape: 'double_border',
    previewGradient: 'from-neutral-700 via-neutral-800 to-black',
    primaryColor: '#a1a1aa',
    description: 'Dark obsidian premium dengan sans-serif Montserrat modern dan bingkai garis ganda.',
    badge: 'Modern Trend',
    tags: ['modern', 'obsidian', 'minimalist'],
  },
  celestial_blue_modern: {
    id: 'celestial_blue_modern',
    name: 'Celestial Ice Blue Modern',
    category: 'modern',
    tagline: 'Kesejukan Langit Biru & Silver',
    themeId: 'celestial_blue',
    fontPairingId: 'modern_clean',
    frameShape: 'double_border',
    previewGradient: 'from-blue-100 via-sky-200 to-blue-400',
    primaryColor: '#3d6e94',
    description: 'Nuansa biru es lembut kontemporer dengan garis ganda modern yang bersih dan segar.',
    badge: '☀️ Modern Cerah',
    tags: ['blue', 'modern', 'cerah'],
  },
};
