import { ThemeDefinition, MasterStyleKitDefinition } from '../types';

export const ROMANTIC_THEMES: Record<string, ThemeDefinition> = {
  rose_gold: {
    id: 'rose_gold',
    name: 'Rose Gold Blush',
    subtitle: 'Romantic Pastel & Soft Pink Glow',
    category: 'romantic',
    mode: 'dark',
    archetype: 'modern_glass',
    primary: '#b76e79',
    secondary: '#e8a598',
    bg: '#0f0a0c',
    cardBg: '#170f12',
    textMain: '#fae8eb',
    textMuted: '#bda1a6',
    border: '#2a1a1f',
    accentBg: '#211419',
    goldFoil: 'linear-gradient(135deg, #f3c1b8 0%, #fae8eb 30%, #b76e79 70%, #d48b94 100%)',
    button: 'bg-gradient-to-r from-[#b76e79] via-[#d48b94] to-[#99555e] hover:opacity-90 text-neutral-950 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#b76e79]/40 text-[#e8a598] hover:bg-[#211419]',
    headerBg: 'bg-[#0f0a0c] text-rose-100',
    previewGradient: 'from-[#b76e79] to-[#63353b]',
    tags: ['rose', 'gold', 'blush', 'pink', 'romantic', 'pastel'],
    palette: {
      primary: '#b76e79',
      secondary: '#e8a598',
      bg: '#0f0a0c',
      cardBg: '#170f12',
      textMain: '#fae8eb',
      textMuted: '#bda1a6',
      border: '#2a1a1f',
      accentBg: '#211419',
      previewGradient: 'from-[#b76e79] to-[#63353b]',
    },
  },
  soft_blush_floral: {
    id: 'soft_blush_floral',
    name: 'Soft Blush Floral',
    subtitle: 'Romantic Petal Pink & Rose Garden Glow',
    category: 'romantic',
    mode: 'light',
    archetype: 'modern_glass',
    primary: '#c4687d',
    secondary: '#e59ca8',
    bg: '#fcf8f9',
    cardBg: '#ffffff',
    textMain: '#26181d',
    textMuted: '#7a5e66',
    border: '#f2dee3',
    accentBg: '#faedf0',
    goldFoil: 'linear-gradient(135deg, #e59ca8 0%, #fff0f3 30%, #c4687d 70%, #b35267 100%)',
    button: 'bg-gradient-to-r from-[#c4687d] via-[#db8497] to-[#b35267] hover:opacity-95 text-white font-bold shadow-md shadow-rose-900/10',
    secondaryButton: 'border-[#c4687d]/40 text-[#c4687d] hover:bg-[#faedf0]',
    headerBg: 'bg-[#fcf8f9] text-neutral-900',
    previewGradient: 'from-[#ffe5eb] via-[#f7b5c4] to-[#c4687d]',
    tags: ['soft', 'blush', 'floral', 'pink', 'rose', 'garden', 'cerah', 'light'],
    palette: {
      primary: '#c4687d',
      secondary: '#e59ca8',
      bg: '#fcf8f9',
      cardBg: '#ffffff',
      textMain: '#26181d',
      textMuted: '#7a5e66',
      border: '#f2dee3',
      accentBg: '#faedf0',
      previewGradient: 'from-[#ffe5eb] via-[#f7b5c4] to-[#c4687d]',
    },
  },
  terracotta_cream: {
    id: 'terracotta_cream',
    name: 'Terracotta Bohemian',
    subtitle: 'Warm Earthy Sunset & Rustic Sand Dune',
    category: 'romantic',
    mode: 'light',
    archetype: 'royal_arch',
    primary: '#b35d3d',
    secondary: '#d98364',
    bg: '#faf6f2',
    cardBg: '#ffffff',
    textMain: '#2a1a14',
    textMuted: '#785b51',
    border: '#eddcd2',
    accentBg: '#f5ebe3',
    goldFoil: 'linear-gradient(135deg, #d98364 0%, #faeee8 30%, #b35d3d 70%, #914529 100%)',
    button: 'bg-gradient-to-r from-[#b35d3d] via-[#cc7352] to-[#99492d] hover:opacity-95 text-white font-bold shadow-md shadow-amber-900/10',
    secondaryButton: 'border-[#b35d3d]/40 text-[#b35d3d] hover:bg-[#f5ebe3]',
    headerBg: 'bg-[#faf6f2] text-neutral-900',
    previewGradient: 'from-[#fceade] via-[#e59b7e] to-[#b35d3d]',
    tags: ['terracotta', 'boho', 'earthy', 'rustic', 'sunset', 'cerah', 'light'],
    palette: {
      primary: '#b35d3d',
      secondary: '#d98364',
      bg: '#faf6f2',
      cardBg: '#ffffff',
      textMain: '#2a1a14',
      textMuted: '#785b51',
      border: '#eddcd2',
      accentBg: '#f5ebe3',
      previewGradient: 'from-[#fceade] via-[#e59b7e] to-[#b35d3d]',
    },
  },
};

export const ROMANTIC_STYLE_KITS: Record<string, MasterStyleKitDefinition> = {
  romantic_rose_calligraphy: {
    id: 'romantic_rose_calligraphy',
    name: 'Romantic Rose Calligraphy',
    category: 'romantic',
    tagline: 'Sentuhan Kaligrafi Romantis Manis',
    themeId: 'rose_gold',
    fontPairingId: 'romantic_calligraphy',
    frameShape: 'soft_oval',
    previewGradient: 'from-rose-500 via-pink-400 to-rose-700',
    primaryColor: '#d67d8f',
    description: 'Blush pink hangat dipadu tulisan tangan bersambung Great Vibes dan bingkai oval lembut.',
    badge: 'Romantis',
    tags: ['rose', 'pink', 'calligraphy'],
  },
  soft_blush_garden: {
    id: 'soft_blush_garden',
    name: 'Soft Blush Floral Romance',
    category: 'romantic',
    tagline: 'Taman Bunga Mawar Lembut',
    themeId: 'soft_blush_floral',
    fontPairingId: 'romantic_calligraphy',
    frameShape: 'soft_oval',
    previewGradient: 'from-pink-100 via-rose-200 to-rose-400',
    primaryColor: '#c4687d',
    description: 'Nuansa pastel pink manis dengan kaligrafi indah, sangat cocok untuk tema garden wedding.',
    badge: '☀️ Romantis Cerah',
    tags: ['blush', 'floral', 'pink', 'garden'],
  },
  terracotta_boho_light: {
    id: 'terracotta_boho_light',
    name: 'Terracotta Bohemian Sunset',
    category: 'romantic',
    tagline: 'Hangatnya Bumi & Senja Bohemian',
    themeId: 'terracotta_cream',
    fontPairingId: 'nusantara_heritage',
    frameShape: 'royal_arch',
    previewGradient: 'from-orange-100 via-amber-200 to-orange-400',
    primaryColor: '#b35d3d',
    description: 'Kombinasi warna terracotta hangat dengan background krem lembut dan tipografi elegan.',
    badge: '☀️ Rustic Boho',
    tags: ['terracotta', 'boho', 'rustic'],
  },
};
