import { ThemeDefinition, MasterStyleKitDefinition } from '../types';

export const ROYAL_THEMES: Record<string, ThemeDefinition> = {
  champagne_gold: {
    id: 'champagne_gold',
    name: 'Champagne Gold',
    subtitle: 'Royal Luxury & Classic Gold Foil',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#c4a661',
    secondary: '#d4af37',
    bg: '#0a0a0b',
    cardBg: '#111115',
    textMain: '#e2e2e7',
    textMuted: '#94949e',
    border: '#1f1f27',
    accentBg: '#181820',
    goldFoil: 'linear-gradient(135deg, #e5c983 0%, #fff4c2 25%, #c4a661 50%, #fef3bd 75%, #a88432 100%)',
    button: 'bg-gradient-to-r from-[#c4a661] via-[#d4af37] to-[#b38728] hover:opacity-90 text-neutral-950 font-bold shadow-lg shadow-black/50',
    secondaryButton: 'border-[#c4a661]/40 text-[#d4af37] hover:bg-[#1f1f27]',
    headerBg: 'bg-[#0a0a0b] text-[#e2e2e7]',
    previewGradient: 'from-[#c4a661] to-[#8a7238]',
    tags: ['royal', 'gold', 'champagne', 'mewah', 'klasik', 'gelap'],
    palette: {
      primary: '#c4a661',
      secondary: '#d4af37',
      bg: '#0a0a0b',
      cardBg: '#111115',
      textMain: '#e2e2e7',
      textMuted: '#94949e',
      border: '#1f1f27',
      accentBg: '#181820',
      previewGradient: 'from-[#c4a661] to-[#8a7238]',
    },
  },
  velvet_navy: {
    id: 'velvet_navy',
    name: 'Velvet Navy',
    subtitle: 'Midnight Deep Blue & Gold Glow',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#243b61',
    secondary: '#d4af37',
    bg: '#070a12',
    cardBg: '#0d1524',
    textMain: '#e2e8f0',
    textMuted: '#889bb4',
    border: '#182740',
    accentBg: '#121c2e',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff3b0 30%, #aa771c 70%, #f5d77f 100%)',
    button: 'bg-gradient-to-r from-[#243b61] via-[#355384] to-[#1a2d4b] hover:opacity-90 text-amber-200 border border-amber-400/40 shadow-lg shadow-black/50',
    secondaryButton: 'border-amber-400/40 text-amber-300 hover:bg-[#121c2e]',
    headerBg: 'bg-[#070a12] text-slate-100',
    previewGradient: 'from-[#243b61] to-[#0f1b2d]',
    tags: ['navy', 'blue', 'midnight', 'royal', 'gold'],
    palette: {
      primary: '#243b61',
      secondary: '#d4af37',
      bg: '#070a12',
      cardBg: '#0d1524',
      textMain: '#e2e8f0',
      textMuted: '#889bb4',
      border: '#182740',
      accentBg: '#121c2e',
      previewGradient: 'from-[#243b61] to-[#0f1b2d]',
    },
  },
  crimson_ruby: {
    id: 'crimson_ruby',
    name: 'Crimson Ruby',
    subtitle: 'Deep Royal Ruby & Golden Crest',
    category: 'royal',
    mode: 'dark',
    archetype: 'royal_arch',
    primary: '#851e2b',
    secondary: '#d4af37',
    bg: '#0d0507',
    cardBg: '#170a0d',
    textMain: '#faedf0',
    textMuted: '#b8949a',
    border: '#2a1016',
    accentBg: '#220b10',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff4c2 30%, #851e2b 70%, #aa771c 100%)',
    button: 'bg-gradient-to-r from-[#851e2b] via-[#a32838] to-[#66131e] hover:opacity-90 text-amber-100 border border-amber-400/30 shadow-lg shadow-black/50',
    secondaryButton: 'border-amber-400/40 text-amber-300 hover:bg-[#220b10]',
    headerBg: 'bg-[#0d0507] text-red-100',
    previewGradient: 'from-[#851e2b] to-[#450911]',
    tags: ['crimson', 'ruby', 'maroon', 'red', 'royal', 'gold'],
    palette: {
      primary: '#851e2b',
      secondary: '#d4af37',
      bg: '#0d0507',
      cardBg: '#170a0d',
      textMain: '#faedf0',
      textMuted: '#b8949a',
      border: '#2a1016',
      accentBg: '#220b10',
      previewGradient: 'from-[#851e2b] to-[#450911]',
    },
  },
  ivory_gold: {
    id: 'ivory_gold',
    name: 'Ivory Gold Pearl',
    subtitle: 'Sacred White Pearl & Champagne Gold Foil',
    category: 'royal',
    mode: 'light',
    archetype: 'royal_arch',
    primary: '#bfa15f',
    secondary: '#d4af37',
    bg: '#faf8f5',
    cardBg: '#ffffff',
    textMain: '#1c1c22',
    textMuted: '#666675',
    border: '#eae4d6',
    accentBg: '#f4eee4',
    goldFoil: 'linear-gradient(135deg, #d4af37 0%, #fff4c2 30%, #bfa15f 70%, #aa771c 100%)',
    button: 'bg-gradient-to-r from-[#bfa15f] via-[#d4af37] to-[#a88944] hover:opacity-95 text-neutral-950 font-bold shadow-md shadow-amber-900/10',
    secondaryButton: 'border-[#bfa15f]/40 text-[#bfa15f] hover:bg-[#f4eee4]',
    headerBg: 'bg-[#faf8f5] text-neutral-900',
    previewGradient: 'from-[#fff4c2] via-[#e5c983] to-[#bfa15f]',
    tags: ['ivory', 'gold', 'pearl', 'putih', 'gading', 'akad', 'cerah', 'light'],
    palette: {
      primary: '#bfa15f',
      secondary: '#d4af37',
      bg: '#faf8f5',
      cardBg: '#ffffff',
      textMain: '#1c1c22',
      textMuted: '#666675',
      border: '#eae4d6',
      accentBg: '#f4eee4',
      previewGradient: 'from-[#fff4c2] via-[#e5c983] to-[#bfa15f]',
    },
  },
};

export const ROYAL_STYLE_KITS: Record<string, MasterStyleKitDefinition> = {
  royal_gold_elegance: {
    id: 'royal_gold_elegance',
    name: 'Royal Gold Elegance',
    category: 'royal',
    tagline: 'Kemewahan Kerajaan Klasik',
    themeId: 'champagne_gold',
    fontPairingId: 'royal_serif',
    frameShape: 'double_border',
    previewGradient: 'from-amber-600 via-yellow-500 to-amber-800',
    primaryColor: '#c4a661',
    description: 'Paduan foil emas mewah, font serif klasik Cinzel, dan bingkai ornamen sudut kotak Art Deco.',
    badge: 'Paling Populer',
    tags: ['gold', 'royal', 'klasik'],
    cornerOrnament: 'art_deco',
  },
  velvet_navy_classic: {
    id: 'velvet_navy_classic',
    name: 'Velvet Navy Majestic',
    category: 'royal',
    tagline: 'Keagungan Biru Navy & Emas',
    themeId: 'velvet_navy',
    fontPairingId: 'royal_serif',
    frameShape: 'double_border',
    previewGradient: 'from-blue-900 via-indigo-800 to-slate-950',
    primaryColor: '#3b82f6',
    description: 'Deep navy keemasan dengan tipografi formal kerajaan dan ornamen sudut kotak berwibawa.',
    badge: 'Eksklusif',
    tags: ['navy', 'blue', 'royal'],
    cornerOrnament: 'art_deco',
  },
  crimson_ruby_luxury: {
    id: 'crimson_ruby_luxury',
    name: 'Crimson Ruby Palace',
    category: 'royal',
    tagline: 'Merah Ruby Mewah & Berani',
    themeId: 'crimson_ruby',
    fontPairingId: 'royal_serif',
    frameShape: 'double_border',
    previewGradient: 'from-red-800 via-rose-700 to-red-950',
    primaryColor: '#e11d48',
    description: 'Merah ruby berani dan mewah dengan ornamen sudut kotak yang melambangkan pesta megah.',
    badge: 'Elegan',
    tags: ['ruby', 'red', 'maroon'],
    cornerOrnament: 'art_deco',
  },
  ivory_pearl_royal: {
    id: 'ivory_pearl_royal',
    name: 'Ivory Pearl Sacred Gold',
    category: 'royal',
    tagline: 'Kemurnian Putih Gading & Emas',
    themeId: 'ivory_gold',
    fontPairingId: 'royal_serif',
    frameShape: 'double_border',
    previewGradient: 'from-amber-100 via-amber-200 to-amber-400',
    primaryColor: '#bfa15f',
    description: 'Latar putih gading bersih dipadu foil emas murni dan ornamen sudut kotak presisi.',
    badge: '☀️ Favorit Cerah',
    tags: ['ivory', 'gold', 'putih', 'cerah'],
    cornerOrnament: 'art_deco',
  },
};
